dist: xenial
language: minimal

services:
  - docker

env:
  - DOCKER_REPO=rtainjapan/rtainjapan-layouts

script:
  - docker build -t $DOCKER_REPO:$TRAVIS_COMMIT --build-arg TYPEKIT_ID=$TYPEKIT_ID .

before_deploy:
  - openssl aes-256-cbc -K $encrypted_609041c98da5_key -iv $encrypted_609041c98da5_iv -in travis/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa

deploy:
  - provider: script
    script: './travis/docker-deploy'
    on:
      branch: master
  - provider: script
    script: './travis/staging-deploy'
    on:
      branch: master

notifications:
  slack:
    secure: ExtzPFHRgAlzZ3AxQqL1uvysudlIZNbmlr1GEAAoxB4GJIpPC7z8jGFm/tmyx5DhE3pk1oZX/iy+j05ad/oVzj1navYVzhTL1D4mPuvoTibrOxuOeVs30pywT1JyP7ZOkwUSLOPQQ3NPSyQlFEiU8dnkn8f9ZwaTWWDXR1FUjvXwJEaMTNeD/rP+k6YVgett79pvFt/ubvAzHh34gJY/Lpj1o7Z32QfzmobiytDp8OG3rCvHs4962hU7+Ob4pxAoKArh1cr39qwq7g43ihJGxP/VmzeUu9DaH9i0tRVvulINMAzzGjRhWDcI6FbNcHuVCHPi6TRQmUURJklC/N8l1rqG/fGYNawfGuDryLtMH3o69/HgF2vUt7DH8Vj+XTmSfduPy1U6pk7Po2iBzkOTp8aZfriFqYGtL3+Sb5STjvc5szwdL8QhquJnERORzw6XINOlNWSNZLwsQR4XeNl5/qGBkcFApQ3tLJqKthj5nBw6qz5eTWK2/SRRiXdXymjaIM2S2f8d5bQi2BClab/WyehDPLqqcoYOMDR/NtoqzBNmaz1hgVL6knr88Kg2T0S3Ej2DmPF9Ltk9dWYX1/Ugbid21lgUUsMq8J01dzg0U6kLnnPvdRTsUzXFSuAVpEw4I3fMrXoAu1v+TDRJMpmma5LwqCqpKXFbRwaUmvACfOI=
