version: '3'
services:
  nodecg:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "9090:9090"
    volumes:
      - ./app:/usr/src/app/bundles/rtainjapan
      - ./cfg:/usr/src/app/cfg
      - /usr/src/app/bundles/rtainjapan/node_modules
      - /usr/src/app/bundles/rtainjapan/bower_components