name: CI

on:
    push:
        branches:
            - master
        tags:
            - '**'
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: ['12', '14']
                os: [windows-latest, ubuntu-20.04]
        env:
            YARN_CACHE_FOLDER: ~/.yarn
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/cache@v2
              with:
                  path: ~/.yarn
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-
            - name: Install
              run: yarn install --frozen-lockfile
            - name: Test
              run: yarn test
            - name: Build
              run: yarn build

    build-image:
        needs: test
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: docker/setup-buildx-action@v1
            - uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: ${{ runner.os }}-buildx-
            - uses: crazy-max/ghaction-docker-meta@v1
              id: docker_meta
              with:
                  images: |
                      rtainjapan/rtainjapan-layouts
                      ghcr.io/rtainjapan/rtainjapan-layouts
                  tag-sha: true
            - uses: docker/login-action@v1
              with:
                  username: hoishin
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: hoishin
                  password: ${{ secrets.CR_TOKEN }}
            - uses: docker/build-push-action@v2
              with:
                  push: true
                  build-args: TYPEKIT_ID=${{ secrets.TYPEKIT_ID }}
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
